export default [
  {
    "HDI rank": 1,
    Country: "Norway",
    "GII Value": 0.053,
    "GII Rank": 6,
    "Maternal mortality ratio": 5,
    "Adolescent birth rate": 5.9,
    "Share of seats in parliament": 39.6,
    "Population with at least some secondary education": 96.1,
    "Labour force participation rate": 61.2
  },
  {
    "HDI rank": 2,
    Country: "Australia",
    "GII Value": 0.12,
    "GII Rank": 24,
    "Maternal mortality ratio": 6,
    "Adolescent birth rate": 14.1,
    "Share of seats in parliament": 30.5,
    "Population with at least some secondary education": 91.4,
    "Labour force participation rate": 58.6
  },
  {
    "HDI rank": 2,
    Country: "Switzerland",
    "GII Value": 0.04,
    "GII Rank": 1,
    "Maternal mortality ratio": 5,
    "Adolescent birth rate": 2.9,
    "Share of seats in parliament": 28.9,
    "Population with at least some secondary education": 96.1,
    "Labour force participation rate": 62.7
  },
  {
    "HDI rank": 4,
    Country: "Germany",
    "GII Value": 0.066,
    "GII Rank": 9,
    "Maternal mortality ratio": 6,
    "Adolescent birth rate": 6.7,
    "Share of seats in parliament": 36.9,
    "Population with at least some secondary education": 96.4,
    "Labour force participation rate": 54.5
  },
  {
    "HDI rank": 5,
    Country: "Denmark",
    "GII Value": 0.041,
    "GII Rank": 2,
    "Maternal mortality ratio": 6,
    "Adolescent birth rate": 4,
    "Share of seats in parliament": 37.4,
    "Population with at least some secondary education": 89.1,
    "Labour force participation rate": 58
  },
  {
    "HDI rank": 5,
    Country: "Singapore",
    "GII Value": 0.068,
    "GII Rank": 11,
    "Maternal mortality ratio": 10,
    "Adolescent birth rate": 3.8,
    "Share of seats in parliament": 23.9,
    "Population with at least some secondary education": 75.5,
    "Labour force participation rate": 58.2
  },
  {
    "HDI rank": 7,
    Country: "Netherlands",
    "GII Value": 0.044,
    "GII Rank": 3,
    "Maternal mortality ratio": 7,
    "Adolescent birth rate": 4,
    "Share of seats in parliament": 36.4,
    "Population with at least some secondary education": 86.2,
    "Labour force participation rate": 57.5
  },
  {
    "HDI rank": 8,
    Country: "Ireland",
    "GII Value": 0.127,
    "GII Rank": 26,
    "Maternal mortality ratio": 8,
    "Adolescent birth rate": 10.4,
    "Share of seats in parliament": 19.9,
    "Population with at least some secondary education": 86.8,
    "Labour force participation rate": 52.4
  },
  {
    "HDI rank": 9,
    Country: "Iceland",
    "GII Value": 0.051,
    "GII Rank": 5,
    "Maternal mortality ratio": 3,
    "Adolescent birth rate": 6.1,
    "Share of seats in parliament": 41.3,
    "Population with at least some secondary education": 100,
    "Labour force participation rate": 70.7
  },
  {
    "HDI rank": 10,
    Country: "Canada",
    "GII Value": 0.098,
    "GII Rank": 18,
    "Maternal mortality ratio": 7,
    "Adolescent birth rate": 9.8,
    "Share of seats in parliament": 28.3,
    "Population with at least some secondary education": 100,
    "Labour force participation rate": 61
  },
  {
    "HDI rank": 10,
    Country: "United States",
    "GII Value": 0.203,
    "GII Rank": 43,
    "Maternal mortality ratio": 14,
    "Adolescent birth rate": 22.6,
    "Share of seats in parliament": 19.5,
    "Population with at least some secondary education": 95.4,
    "Labour force participation rate": 56
  },
  {
    "HDI rank": 12,
    Country: "Hong Kong, China (SAR)",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": "..",
    "Adolescent birth rate": 3.2,
    "Share of seats in parliament": "..",
    "Population with at least some secondary education": 80.9,
    "Labour force participation rate": 53.4
  },
  {
    "HDI rank": 13,
    Country: "New Zealand",
    "GII Value": 0.158,
    "GII Rank": 34,
    "Maternal mortality ratio": 11,
    "Adolescent birth rate": 23.6,
    "Share of seats in parliament": 31.4,
    "Population with at least some secondary education": 98.8,
    "Labour force participation rate": 62.4
  },
  {
    "HDI rank": 14,
    Country: "Sweden",
    "GII Value": 0.048,
    "GII Rank": 4,
    "Maternal mortality ratio": 4,
    "Adolescent birth rate": 5.7,
    "Share of seats in parliament": 43.6,
    "Population with at least some secondary education": 87.8,
    "Labour force participation rate": 60.9
  },
  {
    "HDI rank": 15,
    Country: "Liechtenstein",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": "..",
    "Adolescent birth rate": "..",
    "Share of seats in parliament": 20,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": ".."
  },
  {
    "HDI rank": 16,
    Country: "United Kingdom",
    "GII Value": 0.131,
    "GII Rank": 28,
    "Maternal mortality ratio": 9,
    "Adolescent birth rate": 14.6,
    "Share of seats in parliament": 26.7,
    "Population with at least some secondary education": 81.3,
    "Labour force participation rate": 56.9
  },
  {
    "HDI rank": 17,
    Country: "Japan",
    "GII Value": 0.116,
    "GII Rank": 21,
    "Maternal mortality ratio": 5,
    "Adolescent birth rate": 4.1,
    "Share of seats in parliament": 11.6,
    "Population with at least some secondary education": 93,
    "Labour force participation rate": 49.1
  },
  {
    "HDI rank": 18,
    Country: "Korea",
    "GII Value": 0.067,
    "GII Rank": 10,
    "Maternal mortality ratio": 11,
    "Adolescent birth rate": 1.6,
    "Share of seats in parliament": 16.3,
    "Population with at least some secondary education": 88.8,
    "Labour force participation rate": 50
  },
  {
    "HDI rank": 19,
    Country: "Israel",
    "GII Value": 0.103,
    "GII Rank": 20,
    "Maternal mortality ratio": 5,
    "Adolescent birth rate": 9.7,
    "Share of seats in parliament": 26.7,
    "Population with at least some secondary education": 87.3,
    "Labour force participation rate": 58.9
  },
  {
    "HDI rank": 20,
    Country: "Luxembourg",
    "GII Value": 0.075,
    "GII Rank": 13,
    "Maternal mortality ratio": 10,
    "Adolescent birth rate": 5.9,
    "Share of seats in parliament": 28.3,
    "Population with at least some secondary education": 100.6,
    "Labour force participation rate": 52.2
  },
  {
    "HDI rank": 21,
    Country: "France",
    "GII Value": 0.102,
    "GII Rank": 19,
    "Maternal mortality ratio": 8,
    "Adolescent birth rate": 8.9,
    "Share of seats in parliament": 25.7,
    "Population with at least some secondary education": 79.7,
    "Labour force participation rate": 50.7
  },
  {
    "HDI rank": 22,
    Country: "Belgium",
    "GII Value": 0.073,
    "GII Rank": 12,
    "Maternal mortality ratio": 7,
    "Adolescent birth rate": 8.2,
    "Share of seats in parliament": 42.4,
    "Population with at least some secondary education": 80.1,
    "Labour force participation rate": 48.2
  },
  {
    "HDI rank": 23,
    Country: "Finland",
    "GII Value": 0.056,
    "GII Rank": 8,
    "Maternal mortality ratio": 3,
    "Adolescent birth rate": 6.5,
    "Share of seats in parliament": 41.5,
    "Population with at least some secondary education": 100,
    "Labour force participation rate": 55
  },
  {
    "HDI rank": 24,
    Country: "Austria",
    "GII Value": 0.078,
    "GII Rank": 14,
    "Maternal mortality ratio": 4,
    "Adolescent birth rate": 7.1,
    "Share of seats in parliament": 30.3,
    "Population with at least some secondary education": 98.7,
    "Labour force participation rate": 54.7
  },
  {
    "HDI rank": 25,
    Country: "Slovenia",
    "GII Value": 0.053,
    "GII Rank": 6,
    "Maternal mortality ratio": 9,
    "Adolescent birth rate": 3.8,
    "Share of seats in parliament": 27.7,
    "Population with at least some secondary education": 96.5,
    "Labour force participation rate": 52.2
  },
  {
    "HDI rank": 26,
    Country: "Italy",
    "GII Value": 0.085,
    "GII Rank": 16,
    "Maternal mortality ratio": 4,
    "Adolescent birth rate": 6,
    "Share of seats in parliament": 30.1,
    "Population with at least some secondary education": 79.1,
    "Labour force participation rate": 39.3
  },
  {
    "HDI rank": 27,
    Country: "Spain",
    "GII Value": 0.081,
    "GII Rank": 15,
    "Maternal mortality ratio": 5,
    "Adolescent birth rate": 8.4,
    "Share of seats in parliament": 38,
    "Population with at least some secondary education": 70.9,
    "Labour force participation rate": 52.3
  },
  {
    "HDI rank": 28,
    Country: "Czech Rep.",
    "GII Value": 0.129,
    "GII Rank": 27,
    "Maternal mortality ratio": 4,
    "Adolescent birth rate": 9.9,
    "Share of seats in parliament": 19.6,
    "Population with at least some secondary education": 99.8,
    "Labour force participation rate": 51.1
  },
  {
    "HDI rank": 29,
    Country: "Greece",
    "GII Value": 0.119,
    "GII Rank": 23,
    "Maternal mortality ratio": 3,
    "Adolescent birth rate": 7.5,
    "Share of seats in parliament": 19.7,
    "Population with at least some secondary education": 63.7,
    "Labour force participation rate": 43.9
  },
  {
    "HDI rank": 30,
    Country: "Brunei Darussalam",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 23,
    "Adolescent birth rate": 21,
    "Share of seats in parliament": "..",
    "Population with at least some secondary education": 67.7,
    "Labour force participation rate": 51
  },
  {
    "HDI rank": 30,
    Country: "Estonia",
    "GII Value": 0.131,
    "GII Rank": 28,
    "Maternal mortality ratio": 9,
    "Adolescent birth rate": 13.1,
    "Share of seats in parliament": 23.8,
    "Population with at least some secondary education": 100,
    "Labour force participation rate": 55.4
  },
  {
    "HDI rank": 32,
    Country: "Andorra",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": "..",
    "Adolescent birth rate": "..",
    "Share of seats in parliament": 39.3,
    "Population with at least some secondary education": 72,
    "Labour force participation rate": ".."
  },
  {
    "HDI rank": 33,
    Country: "Cyprus",
    "GII Value": 0.116,
    "GII Rank": 21,
    "Maternal mortality ratio": 7,
    "Adolescent birth rate": 5,
    "Share of seats in parliament": 12.5,
    "Population with at least some secondary education": 77,
    "Labour force participation rate": 57.5
  },
  {
    "HDI rank": 33,
    Country: "Malta",
    "GII Value": 0.217,
    "GII Rank": 44,
    "Maternal mortality ratio": 9,
    "Adolescent birth rate": 16.6,
    "Share of seats in parliament": 12.9,
    "Population with at least some secondary education": 72.7,
    "Labour force participation rate": 38.8
  },
  {
    "HDI rank": 33,
    Country: "Qatar",
    "GII Value": 0.542,
    "GII Rank": 127,
    "Maternal mortality ratio": 13,
    "Adolescent birth rate": 10.7,
    "Share of seats in parliament": 0,
    "Population with at least some secondary education": 70.9,
    "Labour force participation rate": 53.6
  },
  {
    "HDI rank": 36,
    Country: "Poland",
    "GII Value": 0.137,
    "GII Rank": 30,
    "Maternal mortality ratio": 3,
    "Adolescent birth rate": 13.4,
    "Share of seats in parliament": 24.8,
    "Population with at least some secondary education": 81.1,
    "Labour force participation rate": 49.1
  },
  {
    "HDI rank": 37,
    Country: "Lithuania",
    "GII Value": 0.121,
    "GII Rank": 25,
    "Maternal mortality ratio": 10,
    "Adolescent birth rate": 11,
    "Share of seats in parliament": 23.4,
    "Population with at least some secondary education": 91.1,
    "Labour force participation rate": 53.9
  },
  {
    "HDI rank": 38,
    Country: "Chile",
    "GII Value": 0.322,
    "GII Rank": 65,
    "Maternal mortality ratio": 22,
    "Adolescent birth rate": 47.8,
    "Share of seats in parliament": 15.8,
    "Population with at least some secondary education": 76.1,
    "Labour force participation rate": 50.7
  },
  {
    "HDI rank": 38,
    Country: "Saudi Arabia",
    "GII Value": 0.257,
    "GII Rank": 50,
    "Maternal mortality ratio": 12,
    "Adolescent birth rate": 8.8,
    "Share of seats in parliament": 19.9,
    "Population with at least some secondary education": 63.3,
    "Labour force participation rate": 20.1
  },
  {
    "HDI rank": 40,
    Country: "Slovakia",
    "GII Value": 0.179,
    "GII Rank": 39,
    "Maternal mortality ratio": 6,
    "Adolescent birth rate": 20.2,
    "Share of seats in parliament": 18.7,
    "Population with at least some secondary education": 99.2,
    "Labour force participation rate": 51.4
  },
  {
    "HDI rank": 41,
    Country: "Portugal",
    "GII Value": 0.091,
    "GII Rank": 17,
    "Maternal mortality ratio": 10,
    "Adolescent birth rate": 9.9,
    "Share of seats in parliament": 34.8,
    "Population with at least some secondary education": 50.8,
    "Labour force participation rate": 53.6
  },
  {
    "HDI rank": 42,
    Country: "United Arab Emirates",
    "GII Value": 0.232,
    "GII Rank": 46,
    "Maternal mortality ratio": 6,
    "Adolescent birth rate": 29.7,
    "Share of seats in parliament": 22.5,
    "Population with at least some secondary education": 77.4,
    "Labour force participation rate": 41.9
  },
  {
    "HDI rank": 43,
    Country: "Hungary",
    "GII Value": 0.252,
    "GII Rank": 49,
    "Maternal mortality ratio": 17,
    "Adolescent birth rate": 18,
    "Share of seats in parliament": 10.1,
    "Population with at least some secondary education": 95.6,
    "Labour force participation rate": 46.4
  },
  {
    "HDI rank": 44,
    Country: "Latvia",
    "GII Value": 0.191,
    "GII Rank": 41,
    "Maternal mortality ratio": 18,
    "Adolescent birth rate": 13.6,
    "Share of seats in parliament": 18,
    "Population with at least some secondary education": 99.3,
    "Labour force participation rate": 54.4
  },
  {
    "HDI rank": 45,
    Country: "Argentina",
    "GII Value": 0.362,
    "GII Rank": 77,
    "Maternal mortality ratio": 52,
    "Adolescent birth rate": 63.8,
    "Share of seats in parliament": 37.1,
    "Population with at least some secondary education": 63.5,
    "Labour force participation rate": 48.4
  },
  {
    "HDI rank": 45,
    Country: "Croatia",
    "GII Value": 0.141,
    "GII Rank": 31,
    "Maternal mortality ratio": 8,
    "Adolescent birth rate": 9.5,
    "Share of seats in parliament": 15.2,
    "Population with at least some secondary education": 92,
    "Labour force participation rate": 46.4
  },
  {
    "HDI rank": 47,
    Country: "Bahrain",
    "GII Value": 0.233,
    "GII Rank": 48,
    "Maternal mortality ratio": 15,
    "Adolescent birth rate": 13.5,
    "Share of seats in parliament": 15,
    "Population with at least some secondary education": 61.6,
    "Labour force participation rate": 39.2
  },
  {
    "HDI rank": 48,
    Country: "Montenegro",
    "GII Value": 0.156,
    "GII Rank": 33,
    "Maternal mortality ratio": 7,
    "Adolescent birth rate": 12.2,
    "Share of seats in parliament": 17.3,
    "Population with at least some secondary education": 86.9,
    "Labour force participation rate": 42
  },
  {
    "HDI rank": 49,
    Country: "Russia",
    "GII Value": 0.271,
    "GII Rank": 52,
    "Maternal mortality ratio": 25,
    "Adolescent birth rate": 23.4,
    "Share of seats in parliament": 14.5,
    "Population with at least some secondary education": 94.6,
    "Labour force participation rate": 56.6
  },
  {
    "HDI rank": 50,
    Country: "Romania",
    "GII Value": 0.339,
    "GII Rank": 72,
    "Maternal mortality ratio": 31,
    "Adolescent birth rate": 34.6,
    "Share of seats in parliament": 12,
    "Population with at least some secondary education": 86.1,
    "Labour force participation rate": 47.6
  },
  {
    "HDI rank": 51,
    Country: "Kuwait",
    "GII Value": 0.335,
    "GII Rank": 70,
    "Maternal mortality ratio": 4,
    "Adolescent birth rate": 9.8,
    "Share of seats in parliament": 1.5,
    "Population with at least some secondary education": 56.8,
    "Labour force participation rate": 48.4
  },
  {
    "HDI rank": 52,
    Country: "Belarus",
    "GII Value": 0.144,
    "GII Rank": 32,
    "Maternal mortality ratio": 4,
    "Adolescent birth rate": 18.2,
    "Share of seats in parliament": 29.2,
    "Population with at least some secondary education": 87,
    "Labour force participation rate": 54.5
  },
  {
    "HDI rank": 52,
    Country: "Oman",
    "GII Value": 0.281,
    "GII Rank": 54,
    "Maternal mortality ratio": 17,
    "Adolescent birth rate": 8.1,
    "Share of seats in parliament": 8.2,
    "Population with at least some secondary education": 59.8,
    "Labour force participation rate": 30
  },
  {
    "HDI rank": 54,
    Country: "Barbados",
    "GII Value": 0.291,
    "GII Rank": 59,
    "Maternal mortality ratio": 27,
    "Adolescent birth rate": 40.7,
    "Share of seats in parliament": 19.6,
    "Population with at least some secondary education": 93,
    "Labour force participation rate": 62.4
  },
  {
    "HDI rank": 54,
    Country: "Uruguay",
    "GII Value": 0.284,
    "GII Rank": 55,
    "Maternal mortality ratio": 15,
    "Adolescent birth rate": 56.1,
    "Share of seats in parliament": 19.2,
    "Population with at least some secondary education": 55,
    "Labour force participation rate": 55.4
  },
  {
    "HDI rank": 56,
    Country: "Bulgaria",
    "GII Value": 0.223,
    "GII Rank": 45,
    "Maternal mortality ratio": 11,
    "Adolescent birth rate": 37.7,
    "Share of seats in parliament": 20.4,
    "Population with at least some secondary education": 93.1,
    "Labour force participation rate": 48.6
  },
  {
    "HDI rank": 56,
    Country: "Kazakhstan",
    "GII Value": 0.202,
    "GII Rank": 42,
    "Maternal mortality ratio": 12,
    "Adolescent birth rate": 27.9,
    "Share of seats in parliament": 20.1,
    "Population with at least some secondary education": 99.7,
    "Labour force participation rate": 66.1
  },
  {
    "HDI rank": 58,
    Country: "Bahamas",
    "GII Value": 0.362,
    "GII Rank": 77,
    "Maternal mortality ratio": 80,
    "Adolescent birth rate": 29.6,
    "Share of seats in parliament": 16.7,
    "Population with at least some secondary education": 87.4,
    "Labour force participation rate": 69.4
  },
  {
    "HDI rank": 59,
    Country: "Malaysia",
    "GII Value": 0.291,
    "GII Rank": 59,
    "Maternal mortality ratio": 40,
    "Adolescent birth rate": 13.6,
    "Share of seats in parliament": 13.2,
    "Population with at least some secondary education": 75.4,
    "Labour force participation rate": 49.3
  },
  {
    "HDI rank": 60,
    Country: "Palau",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": "..",
    "Adolescent birth rate": "..",
    "Share of seats in parliament": 10.3,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": ".."
  },
  {
    "HDI rank": 60,
    Country: "Panama",
    "GII Value": 0.457,
    "GII Rank": 100,
    "Maternal mortality ratio": 94,
    "Adolescent birth rate": 74.5,
    "Share of seats in parliament": 18.3,
    "Population with at least some secondary education": 70.1,
    "Labour force participation rate": 50.5
  },
  {
    "HDI rank": 62,
    Country: "Antigua and Barbuda",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": "..",
    "Adolescent birth rate": 44.8,
    "Share of seats in parliament": 25.7,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": ".."
  },
  {
    "HDI rank": 63,
    Country: "Seychelles",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": "..",
    "Adolescent birth rate": 57.4,
    "Share of seats in parliament": 43.8,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": ".."
  },
  {
    "HDI rank": 64,
    Country: "Mauritius",
    "GII Value": 0.38,
    "GII Rank": 82,
    "Maternal mortality ratio": 53,
    "Adolescent birth rate": 28.5,
    "Share of seats in parliament": 11.6,
    "Population with at least some secondary education": 57,
    "Labour force participation rate": 46.8
  },
  {
    "HDI rank": 65,
    Country: "Trinidad and Tobago",
    "GII Value": 0.324,
    "GII Rank": 67,
    "Maternal mortality ratio": 63,
    "Adolescent birth rate": 31.5,
    "Share of seats in parliament": 31.5,
    "Population with at least some secondary education": 70.6,
    "Labour force participation rate": 52.6
  },
  {
    "HDI rank": 66,
    Country: "Costa Rica",
    "GII Value": 0.308,
    "GII Rank": 63,
    "Maternal mortality ratio": 25,
    "Adolescent birth rate": 56.5,
    "Share of seats in parliament": 33.3,
    "Population with at least some secondary education": 54.5,
    "Labour force participation rate": 46.8
  },
  {
    "HDI rank": 66,
    Country: "Serbia",
    "GII Value": 0.185,
    "GII Rank": 40,
    "Maternal mortality ratio": 17,
    "Adolescent birth rate": 19,
    "Share of seats in parliament": 34,
    "Population with at least some secondary education": 82.3,
    "Labour force participation rate": 43.4
  },
  {
    "HDI rank": 68,
    Country: "Cuba",
    "GII Value": 0.304,
    "GII Rank": 62,
    "Maternal mortality ratio": 39,
    "Adolescent birth rate": 45.6,
    "Share of seats in parliament": 48.9,
    "Population with at least some secondary education": 83.9,
    "Labour force participation rate": 42.6
  },
  {
    "HDI rank": 69,
    Country: "Iran (Islamic Republic of)",
    "GII Value": 0.509,
    "GII Rank": 118,
    "Maternal mortality ratio": 25,
    "Adolescent birth rate": 26.7,
    "Share of seats in parliament": 3.1,
    "Population with at least some secondary education": 66.8,
    "Labour force participation rate": 16.2
  },
  {
    "HDI rank": 70,
    Country: "Georgia",
    "GII Value": 0.361,
    "GII Rank": 76,
    "Maternal mortality ratio": 36,
    "Adolescent birth rate": 39.7,
    "Share of seats in parliament": 11.3,
    "Population with at least some secondary education": 96.1,
    "Labour force participation rate": 57.3
  },
  {
    "HDI rank": 71,
    Country: "Turkey",
    "GII Value": 0.328,
    "GII Rank": 69,
    "Maternal mortality ratio": 16,
    "Adolescent birth rate": 27.6,
    "Share of seats in parliament": 14.9,
    "Population with at least some secondary education": 43.5,
    "Labour force participation rate": 30.4
  },
  {
    "HDI rank": 71,
    Country: "Venezuela",
    "GII Value": 0.461,
    "GII Rank": 101,
    "Maternal mortality ratio": 95,
    "Adolescent birth rate": 79.4,
    "Share of seats in parliament": 17,
    "Population with at least some secondary education": 72.6,
    "Labour force participation rate": 51.4
  },
  {
    "HDI rank": 73,
    Country: "Sri Lanka",
    "GII Value": 0.386,
    "GII Rank": 87,
    "Maternal mortality ratio": 30,
    "Adolescent birth rate": 14.8,
    "Share of seats in parliament": 4.9,
    "Population with at least some secondary education": 80.2,
    "Labour force participation rate": 30.2
  },
  {
    "HDI rank": 74,
    Country: "Saint Kitts and Nevis",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": "..",
    "Adolescent birth rate": "..",
    "Share of seats in parliament": 13.3,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": ".."
  },
  {
    "HDI rank": 75,
    Country: "Albania",
    "GII Value": 0.267,
    "GII Rank": 51,
    "Maternal mortality ratio": 29,
    "Adolescent birth rate": 21.7,
    "Share of seats in parliament": 20.7,
    "Population with at least some secondary education": 90.2,
    "Labour force participation rate": 40.3
  },
  {
    "HDI rank": 76,
    Country: "Lebanon",
    "GII Value": 0.381,
    "GII Rank": 83,
    "Maternal mortality ratio": 15,
    "Adolescent birth rate": 12.4,
    "Share of seats in parliament": 3.1,
    "Population with at least some secondary education": 53,
    "Labour force participation rate": 23.5
  },
  {
    "HDI rank": 77,
    Country: "Mexico",
    "GII Value": 0.345,
    "GII Rank": 73,
    "Maternal mortality ratio": 38,
    "Adolescent birth rate": 62.8,
    "Share of seats in parliament": 40.6,
    "Population with at least some secondary education": 56.1,
    "Labour force participation rate": 45.4
  },
  {
    "HDI rank": 78,
    Country: "Azerbaijan",
    "GII Value": 0.326,
    "GII Rank": 68,
    "Maternal mortality ratio": 25,
    "Adolescent birth rate": 59.8,
    "Share of seats in parliament": 16.9,
    "Population with at least some secondary education": 93.9,
    "Labour force participation rate": 61.9
  },
  {
    "HDI rank": 79,
    Country: "Brazil",
    "GII Value": 0.414,
    "GII Rank": 92,
    "Maternal mortality ratio": 44,
    "Adolescent birth rate": 67,
    "Share of seats in parliament": 10.8,
    "Population with at least some secondary education": 59.1,
    "Labour force participation rate": 56.3
  },
  {
    "HDI rank": 79,
    Country: "Grenada",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 27,
    "Adolescent birth rate": 30.5,
    "Share of seats in parliament": 25,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": ".."
  },
  {
    "HDI rank": 81,
    Country: "Bosnia and Herz.",
    "GII Value": 0.158,
    "GII Rank": 34,
    "Maternal mortality ratio": 11,
    "Adolescent birth rate": 8.6,
    "Share of seats in parliament": 19.3,
    "Population with at least some secondary education": 69.5,
    "Labour force participation rate": 34.4
  },
  {
    "HDI rank": 82,
    Country: "Macedonia",
    "GII Value": 0.16,
    "GII Rank": 36,
    "Maternal mortality ratio": 8,
    "Adolescent birth rate": 17.6,
    "Share of seats in parliament": 33.3,
    "Population with at least some secondary education": 40.2,
    "Labour force participation rate": 43.9
  },
  {
    "HDI rank": 83,
    Country: "Algeria",
    "GII Value": 0.429,
    "GII Rank": 94,
    "Maternal mortality ratio": 140,
    "Adolescent birth rate": 10.6,
    "Share of seats in parliament": 25.7,
    "Population with at least some secondary education": 34.1,
    "Labour force participation rate": 16.8
  },
  {
    "HDI rank": 84,
    Country: "Armenia",
    "GII Value": 0.293,
    "GII Rank": 61,
    "Maternal mortality ratio": 25,
    "Adolescent birth rate": 23,
    "Share of seats in parliament": 10.7,
    "Population with at least some secondary education": 98.5,
    "Labour force participation rate": 54.9
  },
  {
    "HDI rank": 84,
    Country: "Ukraine",
    "GII Value": 0.284,
    "GII Rank": 55,
    "Maternal mortality ratio": 24,
    "Adolescent birth rate": 24.1,
    "Share of seats in parliament": 12.1,
    "Population with at least some secondary education": 94.3,
    "Labour force participation rate": 52.2
  },
  {
    "HDI rank": 86,
    Country: "Jordan",
    "GII Value": 0.478,
    "GII Rank": 111,
    "Maternal mortality ratio": 58,
    "Adolescent birth rate": 23.2,
    "Share of seats in parliament": 11.6,
    "Population with at least some secondary education": 78.5,
    "Labour force participation rate": 14.2
  },
  {
    "HDI rank": 87,
    Country: "Peru",
    "GII Value": 0.385,
    "GII Rank": 86,
    "Maternal mortality ratio": 68,
    "Adolescent birth rate": 49.1,
    "Share of seats in parliament": 22.3,
    "Population with at least some secondary education": 56.2,
    "Labour force participation rate": 65.7
  },
  {
    "HDI rank": 87,
    Country: "Thailand",
    "GII Value": 0.366,
    "GII Rank": 79,
    "Maternal mortality ratio": 20,
    "Adolescent birth rate": 44.6,
    "Share of seats in parliament": 6.1,
    "Population with at least some secondary education": 40.9,
    "Labour force participation rate": 62.9
  },
  {
    "HDI rank": 89,
    Country: "Ecuador",
    "GII Value": 0.391,
    "GII Rank": 88,
    "Maternal mortality ratio": 64,
    "Adolescent birth rate": 75.9,
    "Share of seats in parliament": 41.6,
    "Population with at least some secondary education": 48.2,
    "Labour force participation rate": 49
  },
  {
    "HDI rank": 90,
    Country: "China",
    "GII Value": 0.164,
    "GII Rank": 37,
    "Maternal mortality ratio": 27,
    "Adolescent birth rate": 7.3,
    "Share of seats in parliament": 23.6,
    "Population with at least some secondary education": 69.8,
    "Labour force participation rate": 63.6
  },
  {
    "HDI rank": 91,
    Country: "Fiji",
    "GII Value": 0.358,
    "GII Rank": 75,
    "Maternal mortality ratio": 30,
    "Adolescent birth rate": 44.8,
    "Share of seats in parliament": 16,
    "Population with at least some secondary education": 73.9,
    "Labour force participation rate": 37
  },
  {
    "HDI rank": 92,
    Country: "Mongolia",
    "GII Value": 0.278,
    "GII Rank": 53,
    "Maternal mortality ratio": 44,
    "Adolescent birth rate": 15.7,
    "Share of seats in parliament": 14.5,
    "Population with at least some secondary education": 89.7,
    "Labour force participation rate": 56.5
  },
  {
    "HDI rank": 92,
    Country: "Saint Lucia",
    "GII Value": 0.354,
    "GII Rank": 74,
    "Maternal mortality ratio": 48,
    "Adolescent birth rate": 53.9,
    "Share of seats in parliament": 20.7,
    "Population with at least some secondary education": 48.2,
    "Labour force participation rate": 63.1
  },
  {
    "HDI rank": 94,
    Country: "Jamaica",
    "GII Value": 0.422,
    "GII Rank": 93,
    "Maternal mortality ratio": 89,
    "Adolescent birth rate": 59.7,
    "Share of seats in parliament": 16.7,
    "Population with at least some secondary education": 67.1,
    "Labour force participation rate": 57.7
  },
  {
    "HDI rank": 95,
    Country: "Colombia",
    "GII Value": 0.393,
    "GII Rank": 89,
    "Maternal mortality ratio": 64,
    "Adolescent birth rate": 50.2,
    "Share of seats in parliament": 20.9,
    "Population with at least some secondary education": 50.3,
    "Labour force participation rate": 57.9
  },
  {
    "HDI rank": 96,
    Country: "Dominica",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": "..",
    "Adolescent birth rate": "..",
    "Share of seats in parliament": 21.9,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": ".."
  },
  {
    "HDI rank": 97,
    Country: "Suriname",
    "GII Value": 0.448,
    "GII Rank": 99,
    "Maternal mortality ratio": 155,
    "Adolescent birth rate": 46.1,
    "Share of seats in parliament": 25.5,
    "Population with at least some secondary education": 57.7,
    "Labour force participation rate": 40.5
  },
  {
    "HDI rank": 97,
    Country: "Tunisia",
    "GII Value": 0.289,
    "GII Rank": 58,
    "Maternal mortality ratio": 62,
    "Adolescent birth rate": 6.8,
    "Share of seats in parliament": 31.3,
    "Population with at least some secondary education": 37.5,
    "Labour force participation rate": 25.1
  },
  {
    "HDI rank": 99,
    Country: "Dominican Republic",
    "GII Value": 0.47,
    "GII Rank": 107,
    "Maternal mortality ratio": 92,
    "Adolescent birth rate": 97.9,
    "Share of seats in parliament": 19.1,
    "Population with at least some secondary education": 57.2,
    "Labour force participation rate": 52.3
  },
  {
    "HDI rank": 99,
    Country: "Saint Vincent and the Grenadines",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 45,
    "Adolescent birth rate": 51,
    "Share of seats in parliament": 13,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 56.3
  },
  {
    "HDI rank": 101,
    Country: "Tonga",
    "GII Value": 0.659,
    "GII Rank": 152,
    "Maternal mortality ratio": 124,
    "Adolescent birth rate": 15.2,
    "Share of seats in parliament": 0,
    "Population with at least some secondary education": 91.2,
    "Labour force participation rate": 52.8
  },
  {
    "HDI rank": 102,
    Country: "Libya",
    "GII Value": 0.167,
    "GII Rank": 38,
    "Maternal mortality ratio": 9,
    "Adolescent birth rate": 6.2,
    "Share of seats in parliament": 16,
    "Population with at least some secondary education": 65.7,
    "Labour force participation rate": 27.8
  },
  {
    "HDI rank": 103,
    Country: "Belize",
    "GII Value": 0.375,
    "GII Rank": 81,
    "Maternal mortality ratio": 28,
    "Adolescent birth rate": 65.9,
    "Share of seats in parliament": 13.3,
    "Population with at least some secondary education": 77.9,
    "Labour force participation rate": 56.3
  },
  {
    "HDI rank": 104,
    Country: "Samoa",
    "GII Value": 0.439,
    "GII Rank": 97,
    "Maternal mortality ratio": 51,
    "Adolescent birth rate": 25,
    "Share of seats in parliament": 6.1,
    "Population with at least some secondary education": 77.8,
    "Labour force participation rate": 23.1
  },
  {
    "HDI rank": 105,
    Country: "Maldives",
    "GII Value": 0.312,
    "GII Rank": 64,
    "Maternal mortality ratio": 68,
    "Adolescent birth rate": 6.7,
    "Share of seats in parliament": 5.9,
    "Population with at least some secondary education": 34.3,
    "Labour force participation rate": 57.3
  },
  {
    "HDI rank": 105,
    Country: "Uzbekistan",
    "GII Value": 0.287,
    "GII Rank": 57,
    "Maternal mortality ratio": 36,
    "Adolescent birth rate": 17.7,
    "Share of seats in parliament": 16.4,
    "Population with at least some secondary education": 99.9,
    "Labour force participation rate": 48.3
  },
  {
    "HDI rank": 107,
    Country: "Moldova (Republic of)",
    "GII Value": 0.232,
    "GII Rank": 46,
    "Maternal mortality ratio": 23,
    "Adolescent birth rate": 22.6,
    "Share of seats in parliament": 21.8,
    "Population with at least some secondary education": 95.2,
    "Labour force participation rate": 38.8
  },
  {
    "HDI rank": 108,
    Country: "Botswana",
    "GII Value": 0.435,
    "GII Rank": 95,
    "Maternal mortality ratio": 129,
    "Adolescent birth rate": 32.3,
    "Share of seats in parliament": 9.5,
    "Population with at least some secondary education": 85.1,
    "Labour force participation rate": 73.4
  },
  {
    "HDI rank": 109,
    Country: "Gabon",
    "GII Value": 0.542,
    "GII Rank": 127,
    "Maternal mortality ratio": 291,
    "Adolescent birth rate": 99.9,
    "Share of seats in parliament": 16,
    "Population with at least some secondary education": 62.3,
    "Labour force participation rate": 39.9
  },
  {
    "HDI rank": 110,
    Country: "Paraguay",
    "GII Value": 0.464,
    "GII Rank": 104,
    "Maternal mortality ratio": 132,
    "Adolescent birth rate": 57.4,
    "Share of seats in parliament": 16.8,
    "Population with at least some secondary education": 46.2,
    "Labour force participation rate": 58.1
  },
  {
    "HDI rank": 111,
    Country: "Egypt",
    "GII Value": 0.565,
    "GII Rank": 135,
    "Maternal mortality ratio": 33,
    "Adolescent birth rate": 51.9,
    "Share of seats in parliament": 2.2,
    "Population with at least some secondary education": 54.5,
    "Labour force participation rate": 22.8
  },
  {
    "HDI rank": 111,
    Country: "Turkmenistan",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 42,
    "Adolescent birth rate": 16.4,
    "Share of seats in parliament": 25.8,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 47.3
  },
  {
    "HDI rank": 113,
    Country: "Indonesia",
    "GII Value": 0.467,
    "GII Rank": 105,
    "Maternal mortality ratio": 126,
    "Adolescent birth rate": 49.6,
    "Share of seats in parliament": 17.1,
    "Population with at least some secondary education": 42.9,
    "Labour force participation rate": 50.9
  },
  {
    "HDI rank": 114,
    Country: "Palestine, State of",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 45,
    "Adolescent birth rate": 58.6,
    "Share of seats in parliament": "..",
    "Population with at least some secondary education": 56.3,
    "Labour force participation rate": 17.8
  },
  {
    "HDI rank": 115,
    Country: "Vietnam",
    "GII Value": 0.337,
    "GII Rank": 71,
    "Maternal mortality ratio": 54,
    "Adolescent birth rate": 38.6,
    "Share of seats in parliament": 24.3,
    "Population with at least some secondary education": 64,
    "Labour force participation rate": 73.8
  },
  {
    "HDI rank": 116,
    Country: "Philippines",
    "GII Value": 0.436,
    "GII Rank": 96,
    "Maternal mortality ratio": 114,
    "Adolescent birth rate": 61.7,
    "Share of seats in parliament": 27.1,
    "Population with at least some secondary education": 72.8,
    "Labour force participation rate": 50.5
  },
  {
    "HDI rank": 117,
    Country: "El Salvador",
    "GII Value": 0.384,
    "GII Rank": 85,
    "Maternal mortality ratio": 54,
    "Adolescent birth rate": 65.2,
    "Share of seats in parliament": 32.1,
    "Population with at least some secondary education": 39.4,
    "Labour force participation rate": 49.1
  },
  {
    "HDI rank": 118,
    Country: "Bolivia (Plurinational State of)",
    "GII Value": 0.446,
    "GII Rank": 98,
    "Maternal mortality ratio": 206,
    "Adolescent birth rate": 70.8,
    "Share of seats in parliament": 51.8,
    "Population with at least some secondary education": 49.6,
    "Labour force participation rate": 63.9
  },
  {
    "HDI rank": 119,
    Country: "South Africa",
    "GII Value": 0.394,
    "GII Rank": 90,
    "Maternal mortality ratio": 138,
    "Adolescent birth rate": 45.5,
    "Share of seats in parliament": 41.2,
    "Population with at least some secondary education": 73.7,
    "Labour force participation rate": 46.2
  },
  {
    "HDI rank": 120,
    Country: "Kyrgyzstan",
    "GII Value": 0.394,
    "GII Rank": 90,
    "Maternal mortality ratio": 76,
    "Adolescent birth rate": 39.6,
    "Share of seats in parliament": 19.2,
    "Population with at least some secondary education": 100,
    "Labour force participation rate": 49.4
  },
  {
    "HDI rank": 121,
    Country: "Iraq",
    "GII Value": 0.525,
    "GII Rank": 123,
    "Maternal mortality ratio": 50,
    "Adolescent birth rate": 84,
    "Share of seats in parliament": 26.5,
    "Population with at least some secondary education": 35.8,
    "Labour force participation rate": 15.1
  },
  {
    "HDI rank": 122,
    Country: "Cabo Verde",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 42,
    "Adolescent birth rate": 73.4,
    "Share of seats in parliament": 20.8,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 53.2
  },
  {
    "HDI rank": 123,
    Country: "Morocco",
    "GII Value": 0.494,
    "GII Rank": 113,
    "Maternal mortality ratio": 121,
    "Adolescent birth rate": 31.7,
    "Share of seats in parliament": 15.7,
    "Population with at least some secondary education": 25.7,
    "Labour force participation rate": 25.3
  },
  {
    "HDI rank": 124,
    Country: "Nicaragua",
    "GII Value": 0.462,
    "GII Rank": 103,
    "Maternal mortality ratio": 150,
    "Adolescent birth rate": 88.8,
    "Share of seats in parliament": 41.3,
    "Population with at least some secondary education": 45.7,
    "Labour force participation rate": 49.1
  },
  {
    "HDI rank": 125,
    Country: "Guatemala",
    "GII Value": 0.494,
    "GII Rank": 113,
    "Maternal mortality ratio": 88,
    "Adolescent birth rate": 80.7,
    "Share of seats in parliament": 13.9,
    "Population with at least some secondary education": 37.4,
    "Labour force participation rate": 41.3
  },
  {
    "HDI rank": 125,
    Country: "Namibia",
    "GII Value": 0.474,
    "GII Rank": 108,
    "Maternal mortality ratio": 265,
    "Adolescent birth rate": 76.8,
    "Share of seats in parliament": 37.7,
    "Population with at least some secondary education": 38.1,
    "Labour force participation rate": 55.7
  },
  {
    "HDI rank": 127,
    Country: "Guyana",
    "GII Value": 0.508,
    "GII Rank": 117,
    "Maternal mortality ratio": 229,
    "Adolescent birth rate": 88,
    "Share of seats in parliament": 30.4,
    "Population with at least some secondary education": 68.1,
    "Labour force participation rate": 41.8
  },
  {
    "HDI rank": 127,
    Country: "Micronesia (Federated States of)",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 100,
    "Adolescent birth rate": 15,
    "Share of seats in parliament": 0,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": ".."
  },
  {
    "HDI rank": 129,
    Country: "Tajikistan",
    "GII Value": 0.322,
    "GII Rank": 65,
    "Maternal mortality ratio": 32,
    "Adolescent birth rate": 38.1,
    "Share of seats in parliament": 14.7,
    "Population with at least some secondary education": 98.1,
    "Labour force participation rate": 59.4
  },
  {
    "HDI rank": 130,
    Country: "Honduras",
    "GII Value": 0.461,
    "GII Rank": 101,
    "Maternal mortality ratio": 129,
    "Adolescent birth rate": 65,
    "Share of seats in parliament": 25.8,
    "Population with at least some secondary education": 33.4,
    "Labour force participation rate": 47.2
  },
  {
    "HDI rank": 131,
    Country: "India",
    "GII Value": 0.53,
    "GII Rank": 125,
    "Maternal mortality ratio": 174,
    "Adolescent birth rate": 24.5,
    "Share of seats in parliament": 12.2,
    "Population with at least some secondary education": 35.3,
    "Labour force participation rate": 26.8
  },
  {
    "HDI rank": 132,
    Country: "Bhutan",
    "GII Value": 0.477,
    "GII Rank": 110,
    "Maternal mortality ratio": 148,
    "Adolescent birth rate": 21.4,
    "Share of seats in parliament": 8.3,
    "Population with at least some secondary education": 5.8,
    "Labour force participation rate": 58.7
  },
  {
    "HDI rank": 133,
    Country: "Timor-Leste",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 215,
    "Adolescent birth rate": 46.6,
    "Share of seats in parliament": 38.5,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 26.8
  },
  {
    "HDI rank": 134,
    Country: "Vanuatu",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 78,
    "Adolescent birth rate": 43.1,
    "Share of seats in parliament": 0,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 61.6
  },
  {
    "HDI rank": 135,
    Country: "Congo",
    "GII Value": 0.592,
    "GII Rank": 141,
    "Maternal mortality ratio": 442,
    "Adolescent birth rate": 117.7,
    "Share of seats in parliament": 11.5,
    "Population with at least some secondary education": 45,
    "Labour force participation rate": 67.1
  },
  {
    "HDI rank": 135,
    Country: "Equatorial Guinea",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 342,
    "Adolescent birth rate": 108.7,
    "Share of seats in parliament": 19.7,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 71.3
  },
  {
    "HDI rank": 137,
    Country: "Kiribati",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 90,
    "Adolescent birth rate": 17.2,
    "Share of seats in parliament": 8.7,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": ".."
  },
  {
    "HDI rank": 138,
    Country: "Lao People's Democratic Republic",
    "GII Value": 0.468,
    "GII Rank": 106,
    "Maternal mortality ratio": 197,
    "Adolescent birth rate": 64.1,
    "Share of seats in parliament": 25,
    "Population with at least some secondary education": 30.4,
    "Labour force participation rate": 77.7
  },
  {
    "HDI rank": 139,
    Country: "Bangladesh",
    "GII Value": 0.52,
    "GII Rank": 119,
    "Maternal mortality ratio": 176,
    "Adolescent birth rate": 83,
    "Share of seats in parliament": 20,
    "Population with at least some secondary education": 42,
    "Labour force participation rate": 43.1
  },
  {
    "HDI rank": 139,
    Country: "Ghana",
    "GII Value": 0.547,
    "GII Rank": 131,
    "Maternal mortality ratio": 319,
    "Adolescent birth rate": 66.8,
    "Share of seats in parliament": 10.9,
    "Population with at least some secondary education": 51.8,
    "Labour force participation rate": 75.5
  },
  {
    "HDI rank": 139,
    Country: "Zambia",
    "GII Value": 0.526,
    "GII Rank": 124,
    "Maternal mortality ratio": 224,
    "Adolescent birth rate": 90.4,
    "Share of seats in parliament": 12.7,
    "Population with at least some secondary education": 52.3,
    "Labour force participation rate": 69.8
  },
  {
    "HDI rank": 142,
    Country: "Sao Tome and Principe",
    "GII Value": 0.524,
    "GII Rank": 122,
    "Maternal mortality ratio": 156,
    "Adolescent birth rate": 84.3,
    "Share of seats in parliament": 18.2,
    "Population with at least some secondary education": 30.8,
    "Labour force participation rate": 45.3
  },
  {
    "HDI rank": 143,
    Country: "Cambodia",
    "GII Value": 0.479,
    "GII Rank": 112,
    "Maternal mortality ratio": 161,
    "Adolescent birth rate": 51.6,
    "Share of seats in parliament": 19,
    "Population with at least some secondary education": 13.2,
    "Labour force participation rate": 75.5
  },
  {
    "HDI rank": 144,
    Country: "Nepal",
    "GII Value": 0.497,
    "GII Rank": 115,
    "Maternal mortality ratio": 258,
    "Adolescent birth rate": 71.9,
    "Share of seats in parliament": 29.5,
    "Population with at least some secondary education": 24.1,
    "Labour force participation rate": 79.7
  },
  {
    "HDI rank": 145,
    Country: "Myanmar",
    "GII Value": 0.374,
    "GII Rank": 80,
    "Maternal mortality ratio": 178,
    "Adolescent birth rate": 16.5,
    "Share of seats in parliament": 13,
    "Population with at least some secondary education": 27.1,
    "Labour force participation rate": 75.1
  },
  {
    "HDI rank": 146,
    Country: "Kenya",
    "GII Value": 0.565,
    "GII Rank": 135,
    "Maternal mortality ratio": 510,
    "Adolescent birth rate": 90.9,
    "Share of seats in parliament": 20.8,
    "Population with at least some secondary education": 27.8,
    "Labour force participation rate": 62.1
  },
  {
    "HDI rank": 147,
    Country: "Pakistan",
    "GII Value": 0.546,
    "GII Rank": 130,
    "Maternal mortality ratio": 178,
    "Adolescent birth rate": 38.7,
    "Share of seats in parliament": 20,
    "Population with at least some secondary education": 26.5,
    "Labour force participation rate": 24.3
  },
  {
    "HDI rank": 148,
    Country: "Swaziland",
    "GII Value": 0.566,
    "GII Rank": 137,
    "Maternal mortality ratio": 389,
    "Adolescent birth rate": 70.4,
    "Share of seats in parliament": 14.7,
    "Population with at least some secondary education": 27.3,
    "Labour force participation rate": 40
  },
  {
    "HDI rank": 149,
    Country: "Syrian Arab Republic",
    "GII Value": 0.554,
    "GII Rank": 133,
    "Maternal mortality ratio": 68,
    "Adolescent birth rate": 39.4,
    "Share of seats in parliament": 12.4,
    "Population with at least some secondary education": 34.8,
    "Labour force participation rate": 12.2
  },
  {
    "HDI rank": 150,
    Country: "Angola",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 477,
    "Adolescent birth rate": 164.3,
    "Share of seats in parliament": 36.8,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 59.9
  },
  {
    "HDI rank": 151,
    Country: "Tanzania",
    "GII Value": 0.544,
    "GII Rank": 129,
    "Maternal mortality ratio": 398,
    "Adolescent birth rate": 118.6,
    "Share of seats in parliament": 36,
    "Population with at least some secondary education": 10.1,
    "Labour force participation rate": 74
  },
  {
    "HDI rank": 152,
    Country: "Nigeria",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 814,
    "Adolescent birth rate": 110.6,
    "Share of seats in parliament": 5.8,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 48.4
  },
  {
    "HDI rank": 153,
    Country: "Cameroon",
    "GII Value": 0.568,
    "GII Rank": 138,
    "Maternal mortality ratio": 596,
    "Adolescent birth rate": 104.6,
    "Share of seats in parliament": 27.1,
    "Population with at least some secondary education": 31.7,
    "Labour force participation rate": 71
  },
  {
    "HDI rank": 154,
    Country: "Papua New Guinea",
    "GII Value": 0.595,
    "GII Rank": 143,
    "Maternal mortality ratio": 215,
    "Adolescent birth rate": 54.8,
    "Share of seats in parliament": 2.7,
    "Population with at least some secondary education": 8.8,
    "Labour force participation rate": 69.6
  },
  {
    "HDI rank": 154,
    Country: "Zimbabwe",
    "GII Value": 0.54,
    "GII Rank": 126,
    "Maternal mortality ratio": 443,
    "Adolescent birth rate": 109.7,
    "Share of seats in parliament": 35.1,
    "Population with at least some secondary education": 51.9,
    "Labour force participation rate": 77.8
  },
  {
    "HDI rank": 156,
    Country: "Solomon Islands",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 114,
    "Adolescent birth rate": 48.4,
    "Share of seats in parliament": 2,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 61.1
  },
  {
    "HDI rank": 157,
    Country: "Mauritania",
    "GII Value": 0.626,
    "GII Rank": 147,
    "Maternal mortality ratio": 602,
    "Adolescent birth rate": 78.6,
    "Share of seats in parliament": 22.2,
    "Population with at least some secondary education": 11.1,
    "Labour force participation rate": 29.1
  },
  {
    "HDI rank": 158,
    Country: "Madagascar",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 353,
    "Adolescent birth rate": 116.2,
    "Share of seats in parliament": 20.5,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 83.8
  },
  {
    "HDI rank": 159,
    Country: "Rwanda",
    "GII Value": 0.383,
    "GII Rank": 84,
    "Maternal mortality ratio": 290,
    "Adolescent birth rate": 26.3,
    "Share of seats in parliament": 57.5,
    "Population with at least some secondary education": 10.5,
    "Labour force participation rate": 86.4
  },
  {
    "HDI rank": 160,
    Country: "Comoros",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 335,
    "Adolescent birth rate": 68.3,
    "Share of seats in parliament": 3,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 35.3
  },
  {
    "HDI rank": 160,
    Country: "Lesotho",
    "GII Value": 0.549,
    "GII Rank": 132,
    "Maternal mortality ratio": 487,
    "Adolescent birth rate": 92.7,
    "Share of seats in parliament": 24.8,
    "Population with at least some secondary education": 23.6,
    "Labour force participation rate": 59.2
  },
  {
    "HDI rank": 162,
    Country: "Senegal",
    "GII Value": 0.521,
    "GII Rank": 120,
    "Maternal mortality ratio": 315,
    "Adolescent birth rate": 78.6,
    "Share of seats in parliament": 42.7,
    "Population with at least some secondary education": 10.2,
    "Labour force participation rate": 45
  },
  {
    "HDI rank": 163,
    Country: "Haiti",
    "GII Value": 0.593,
    "GII Rank": 142,
    "Maternal mortality ratio": 359,
    "Adolescent birth rate": 39.3,
    "Share of seats in parliament": 3.5,
    "Population with at least some secondary education": 25.7,
    "Labour force participation rate": 61.5
  },
  {
    "HDI rank": 163,
    Country: "Uganda",
    "GII Value": 0.522,
    "GII Rank": 121,
    "Maternal mortality ratio": 343,
    "Adolescent birth rate": 111.9,
    "Share of seats in parliament": 35,
    "Population with at least some secondary education": 25.9,
    "Labour force participation rate": 82.3
  },
  {
    "HDI rank": 165,
    Country: "Sudan",
    "GII Value": 0.575,
    "GII Rank": 140,
    "Maternal mortality ratio": 311,
    "Adolescent birth rate": 74,
    "Share of seats in parliament": 31,
    "Population with at least some secondary education": 13.7,
    "Labour force participation rate": 24.3
  },
  {
    "HDI rank": 166,
    Country: "Togo",
    "GII Value": 0.556,
    "GII Rank": 134,
    "Maternal mortality ratio": 368,
    "Adolescent birth rate": 92,
    "Share of seats in parliament": 17.6,
    "Population with at least some secondary education": 23.1,
    "Labour force participation rate": 81.1
  },
  {
    "HDI rank": 167,
    Country: "Benin",
    "GII Value": 0.613,
    "GII Rank": 144,
    "Maternal mortality ratio": 405,
    "Adolescent birth rate": 83.2,
    "Share of seats in parliament": 7.2,
    "Population with at least some secondary education": 15.8,
    "Labour force participation rate": 70
  },
  {
    "HDI rank": 168,
    Country: "Yemen",
    "GII Value": 0.767,
    "GII Rank": 159,
    "Maternal mortality ratio": 385,
    "Adolescent birth rate": 61.5,
    "Share of seats in parliament": 0.5,
    "Population with at least some secondary education": 15.6,
    "Labour force participation rate": 25.8
  },
  {
    "HDI rank": 169,
    Country: "Afghanistan",
    "GII Value": 0.667,
    "GII Rank": 154,
    "Maternal mortality ratio": 396,
    "Adolescent birth rate": 74,
    "Share of seats in parliament": 27.4,
    "Population with at least some secondary education": 8.8,
    "Labour force participation rate": 19.1
  },
  {
    "HDI rank": 170,
    Country: "Malawi",
    "GII Value": 0.614,
    "GII Rank": 145,
    "Maternal mortality ratio": 634,
    "Adolescent birth rate": 136.2,
    "Share of seats in parliament": 16.7,
    "Population with at least some secondary education": 14.9,
    "Labour force participation rate": 81.2
  },
  {
    "HDI rank": 171,
    Country: "Côte d'Ivoire",
    "GII Value": 0.672,
    "GII Rank": 155,
    "Maternal mortality ratio": 645,
    "Adolescent birth rate": 135.5,
    "Share of seats in parliament": 9.2,
    "Population with at least some secondary education": 16.6,
    "Labour force participation rate": 52.4
  },
  {
    "HDI rank": 172,
    Country: "Djibouti",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 229,
    "Adolescent birth rate": 21.5,
    "Share of seats in parliament": 12.7,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 36.5
  },
  {
    "HDI rank": 173,
    Country: "Gambia",
    "GII Value": 0.641,
    "GII Rank": 148,
    "Maternal mortality ratio": 706,
    "Adolescent birth rate": 113,
    "Share of seats in parliament": 9.4,
    "Population with at least some secondary education": 25.3,
    "Labour force participation rate": 72.2
  },
  {
    "HDI rank": 174,
    Country: "Ethiopia",
    "GII Value": 0.499,
    "GII Rank": 116,
    "Maternal mortality ratio": 353,
    "Adolescent birth rate": 58.4,
    "Share of seats in parliament": 37.3,
    "Population with at least some secondary education": 10.8,
    "Labour force participation rate": 77
  },
  {
    "HDI rank": 175,
    Country: "Mali",
    "GII Value": 0.689,
    "GII Rank": 156,
    "Maternal mortality ratio": 587,
    "Adolescent birth rate": 174.6,
    "Share of seats in parliament": 8.8,
    "Population with at least some secondary education": 7.3,
    "Labour force participation rate": 50.1
  },
  {
    "HDI rank": 176,
    Country: "Congo (Democratic Republic of the)",
    "GII Value": 0.663,
    "GII Rank": 153,
    "Maternal mortality ratio": 693,
    "Adolescent birth rate": 122.6,
    "Share of seats in parliament": 8.2,
    "Population with at least some secondary education": 14.5,
    "Labour force participation rate": 70.5
  },
  {
    "HDI rank": 177,
    Country: "Liberia",
    "GII Value": 0.649,
    "GII Rank": 150,
    "Maternal mortality ratio": 725,
    "Adolescent birth rate": 108.8,
    "Share of seats in parliament": 10.7,
    "Population with at least some secondary education": 17.3,
    "Labour force participation rate": 58
  },
  {
    "HDI rank": 178,
    Country: "Guinea-Bissau",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 549,
    "Adolescent birth rate": 89.5,
    "Share of seats in parliament": 13.7,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 67.2
  },
  {
    "HDI rank": 179,
    Country: "Eritrea",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 501,
    "Adolescent birth rate": 54.3,
    "Share of seats in parliament": 22,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 77.7
  },
  {
    "HDI rank": 179,
    Country: "Sierra Leone",
    "GII Value": 0.65,
    "GII Rank": 151,
    "Maternal mortality ratio": "1,360",
    "Adolescent birth rate": 118.2,
    "Share of seats in parliament": 12.4,
    "Population with at least some secondary education": 16.8,
    "Labour force participation rate": 65
  },
  {
    "HDI rank": 181,
    Country: "Mozambique",
    "GII Value": 0.574,
    "GII Rank": 139,
    "Maternal mortality ratio": 489,
    "Adolescent birth rate": 139.7,
    "Share of seats in parliament": 39.6,
    "Population with at least some secondary education": 2.8,
    "Labour force participation rate": 82.5
  },
  {
    "HDI rank": 181,
    Country: "South Sudan",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 789,
    "Adolescent birth rate": 65.9,
    "Share of seats in parliament": 24.3,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 71.2
  },
  {
    "HDI rank": 183,
    Country: "Guinea",
    "GII Value": "..",
    "GII Rank": "..",
    "Maternal mortality ratio": 679,
    "Adolescent birth rate": 140.6,
    "Share of seats in parliament": 21.9,
    "Population with at least some secondary education": "..",
    "Labour force participation rate": 79.5
  },
  {
    "HDI rank": 184,
    Country: "Burundi",
    "GII Value": 0.474,
    "GII Rank": 108,
    "Maternal mortality ratio": 712,
    "Adolescent birth rate": 28.3,
    "Share of seats in parliament": 37.8,
    "Population with at least some secondary education": 7.1,
    "Labour force participation rate": 84.6
  },
  {
    "HDI rank": 185,
    Country: "Burkina Faso",
    "GII Value": 0.615,
    "GII Rank": 146,
    "Maternal mortality ratio": 371,
    "Adolescent birth rate": 108.5,
    "Share of seats in parliament": 9.4,
    "Population with at least some secondary education": 6,
    "Labour force participation rate": 76.6
  },
  {
    "HDI rank": 186,
    Country: "Chad",
    "GII Value": 0.695,
    "GII Rank": 157,
    "Maternal mortality ratio": 856,
    "Adolescent birth rate": 133.5,
    "Share of seats in parliament": 14.9,
    "Population with at least some secondary education": 1.7,
    "Labour force participation rate": 64
  },
  {
    "HDI rank": 187,
    Country: "Niger",
    "GII Value": 0.695,
    "GII Rank": 157,
    "Maternal mortality ratio": 553,
    "Adolescent birth rate": 202.4,
    "Share of seats in parliament": 13.3,
    "Population with at least some secondary education": 3.6,
    "Labour force participation rate": 40.2
  },
  {
    "HDI rank": 188,
    Country: "Central African Republic",
    "GII Value": 0.648,
    "GII Rank": 149,
    "Maternal mortality ratio": 882,
    "Adolescent birth rate": 91.9,
    "Share of seats in parliament": 12.5,
    "Population with at least some secondary education": 12.3,
    "Labour force participation rate": 71.7
  }
];
